spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SnakeMrLiu/CloudLiu
          username:
          password:
      label: master
server:
  port: ${port:8764}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/